### PR TITLE
Simple cube of a number generator with prompt.

### PR DESCRIPTION
**Pull request by hrishikeshps**
Hrishikesh simple cube number generator

### CODE REVIEW

**Review by janusjerom — CHANGES_REQUESTED** [review]
Please use :
// PROGRAM-NAME : Print 'Hello World' !
// By John Doe
//PROGRAM-CODE :

as your file format. Explanation can be found in Contributing.md

**Comment by hrishikeshps** [comment]
@janusjerom I have added the author and program name as per instructions.

**Comment by hrishikeshps** [comment]
Thanks. I have added the author name and program name as per instructions.

Hrishikesh Sharma
+919876011554

**Review by janusjerom — APPROVED** [review]
Thank you for your PR

**Pull request merged**
