### PR TITLE
feat: add meaning of life in dart

### PR DESCRIPTION
**Pull request by LRNZ09**
42

### CODE REVIEW

**Review by janusjerom — CHANGES_REQUESTED** [review]
add file format

**Comment by LRNZ09** [comment]
@janusjerom what kind of format?

**Comment by janusjerom** [comment]
> 
> 
> @janusjerom what kind of format?

Make sure to use the correct method for commenting in dart
// PROGRAM-NAME : program name
// BY your name
// PROGRAM-CODE :

**Comment by LRNZ09** [comment]
@janusjerom it should be ok now

**Review by janusjerom — APPROVED** [review]
Thank you for your PR.

**Pull request merged**
